### PR TITLE
Update producer.json

### PR DESCRIPTION
**Pull request by lennondtps**
Add `static_routing_key` property for amqp producer

### CODE REVIEW

**Comment by lennondtps** [comment]
Hello @alombarte! I thought this could be a Patch Version `2.4.4` instead of a `2.5` version.
Do you have a roadmap for the next version?

BTW didn't mention that this change is related to this PR https://github.com/krakend/krakend-amqp/pull/22

**Comment by alombarte** [comment]
Hi @lennondtps, patches should not contain new functionality.

We will release this in 2.5 as the roadmap is almost finished

**Review by alombarte — CHANGES_REQUESTED** [review]
Thank you very much for the code changes and the schema changes. This is an end-to-end functionality!

Reviewing this code, shouldn't the `static_routing_key` be a boolean instead? Also, the `default` attribute should respect the declared type. Now it is a string.

Finally, I have created the new v2.5. If you can copy this file to `v2.5/backend/amqp/producer.json` and revert the changes to v2.4, this is ready to merge.

**Comment by lennondtps** [comment]
You are right @alombarte  I updated the code :)

**Comment by lennondtps** [comment]
Hello @alombarte. You are right about the boolean! I made the changes for the v2.5 folder :)

**Review by alombarte — APPROVED** [review]

**Comment by alombarte** [comment]
Awesome! Thank you for this!

**Pull request merged**
