### PR TITLE
Massive test case sample

### PR DESCRIPTION
**Pull request by alombarte**
Hi @jviotti ,

I wanted to do stress a little bit more the `test` command of the `jsonschema` tool and add a lot of data to it. As generating all the tests is very time consuming and I had a testing mechanism in place, I have moved the files I used to check the complete integration in VS Code as test files (I just wrapped around the `data: {}`). You'll find these files under `test/v2.6/*.json`. 

The test works ok and takes around **9 seconds** to execute the three tests. The `all.json` is the one I added to stress the system. It is a single test that checks a sample schema with (almost) all possible properties.

This file should be split into several files, but so far, it brings a lot of value as is.

I am pushing this to improve the system, feel free to do any modifications to this branch. This is the output I get right now:
```
jsonschema test test/v2.7 --resolve v2.7          
/workspace/test/v2.7/modifier/jmespath.json
    JMESPath - the empty object is invalid
        PASS
    JMESPath - example expression
        PASS
/workspace/test/v2.7/all.json
    Full JSON Schema test - Full test-case
        FAIL
/workspace/test/v2.7/e2e.json
    E2E test - Full test-case
        PASS
/workspace/test/v2.7/flexible_config.json
    Flexible config test - Full test-case
        PASS
```
As you can see the big test fails, but I see no way (even with `--verbose`) to know the reason of a failing test. Of course I can debug this by playing with the `data: {}` field. For instance `"data": { "version": 3 }` passes

I don't know if it's possible but it would be very useful to print the conflicting part of the test explaining the reason.

### CODE REVIEW

**Comment by jviotti** [comment]
@alombarte You are correct. We should be printing validation results on failure, not sure why I didn't think about that. Can you upgrade to v1.1.1 on this PR? You should already be seeing validation output with that.

As a word of warning, the human-friendly messages on our implementation are a bit terrible right (we know, and we are fixing it very soon 😅) but at least you will be able to see the problematic schema and instance locations.

Let me separately dig into the 9s performance problem.

**Comment by jviotti** [comment]
OK, so as I initially expected, all of that time is getting spent on the compiler. Essentially, what we do for performance reasons (to achieve the performance I showed-off on LinkedIn recently), is to pre-compile schemas into an intermediary lower-level format that we later evaluate. The idea is that we do a lot of complex computation once, and then evaluating the result is super fast.

That said, 9 seconds to compile a schema (6 seconds on my machine) is a lot. Let me do some proper profiling. I believe there are low hanging fruits, as we never spent any time optimising the compiler (vs the evaluator).

**Comment by alombarte** [comment]
Thank you!

I can help you define and go through the messages to make them more human-friendly if you want. With the new release the errors were shown.

There was **ONE** error in the schema, but still, it printed this:

```
/workspace/test/v2.7/all.json
    Full JSON Schema test - Full test-case
        FAIL

error: The target object is expected to define the given property
  at instance location "/async_agent/0/backend/0/extra_config/backend~1http"
  at evaluate path "/properties/async_agent/$ref/items/properties/backend/items/$ref/properties/extra_config/$ref/properties/backend~1http/oneOf/0/required"
error: The target object is expected to define the given property
  at instance location "/async_agent/0/backend/0/extra_config/modifier~1body-generator"
  at evaluate path "/properties/async_agent/$ref/items/properties/backend/items/$ref/properties/extra_config/$ref/properties/modifier~1body-generator/$ref/oneOf/0/required"
error: The target object is expected to define the given property
  at instance location "/async_agent/0/backend/0/extra_config/modifier~1response-body-generator"
  at evaluate path "/properties/async_agent/$ref/items/properties/backend/items/$ref/properties/extra_config/$ref/properties/modifier~1response-body-generator/$ref/oneOf/0/required"
error: The target object is expected to define the given property
  at instance location "/endpoints/2/extra_config/modifier~1response-body-generator"
  at evaluate path "/properties/endpoints/items/$ref/properties/extra_config/$ref/properties/modifier~1response-body-generator/$ref/oneOf/0/required"
error: The target object is expected to define all of the given properties
  at instance location "/endpoints/4/backend/0/extra_config/backend~1graphql"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items/$ref/properties/extra_config/$ref/properties/backend~1graphql/$ref/oneOf/0/required"
error: Abort evaluation on failure
  at instance location "/endpoints/4/backend/0/extra_config/modifier~1martian/@extra_comment"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items/$ref/properties/extra_config/$ref/properties/modifier~1martian/$ref/additionalProperties"
error: Loop over the properties of the target object
  at instance location "/endpoints/4/backend/0/extra_config/modifier~1martian"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items/$ref/properties/extra_config/$ref/properties/modifier~1martian/$ref/additionalProperties"
error: Mark the current position of the evaluation process for future jumps
  at instance location "/endpoints/4/backend/0/extra_config/modifier~1martian"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items/$ref/properties/extra_config/$ref/properties/modifier~1martian/$ref"
error: The target is expected to match all of the given assertions
  at instance location "/endpoints/4/backend/0/extra_config"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items/$ref/properties/extra_config/$ref/properties"
error: Mark the current position of the evaluation process for future jumps
  at instance location "/endpoints/4/backend/0/extra_config"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items/$ref/properties/extra_config/$ref"
error: The target is expected to match all of the given assertions
  at instance location "/endpoints/4/backend/0"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items/$ref/properties"
error: Mark the current position of the evaluation process for future jumps
  at instance location "/endpoints/4/backend/0"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items/$ref"
error: Loop over the items of the target array
  at instance location "/endpoints/4/backend"
  at evaluate path "/properties/endpoints/items/$ref/properties/backend/items"
error: The target is expected to match all of the given assertions
  at instance location "/endpoints/4"
  at evaluate path "/properties/endpoints/items/$ref/properties"
error: Mark the current position of the evaluation process for future jumps
  at instance location "/endpoints/4"
  at evaluate path "/properties/endpoints/items/$ref"
error: Loop over the items of the target array
  at instance location "/endpoints"
  at evaluate path "/properties/endpoints/items"
error: The target is expected to match all of the given assertions
  at instance location ""
  at evaluate path "/properties"
```
The first errors pointed to the `oneOf` property in the subcomponents of the `async_agent` field, so I spent a few minutes figuring out what was happening. In the end, there was no problem at all with the `oneOf`, and not even with the `async_agent`. The error of the `endpoints` object and the `modifier/martian` was the one failing because it had a non-permitted additional property. A misplaced attribute (as you can see in the last commit) was all, but the trace pointed to many places in the evaluation cascade, even places were the schema was correct, making it difficult to debug.

The `oneOf` evaluation is greedy and is printing errors that are not related. I will merge this tests now.

**Comment by jviotti** [comment]
Yeah, you are seeing the stack trace for a single error, which we can probably present more nicely. I guess having the `error:` prefix on every frame doesn't help 😅 

On `oneOf` being greedy, etc you are correct. This is part of the work needed to revamp the current validation output, which is a total mess. I promise it will get very nice very soon :)

**Comment by alombarte** [comment]
Maybe adding a line at the beginning saying that what comes next is a **stack trace** would be enough.

**Comment by jviotti** [comment]
Makes sense! It will get cleaner on the next version

**Pull request merged**
